---
development:
  cloud_name: dno0dwbro
  api_key: '117934122311229'
  api_secret: Bt069STFYET5DMuoVbS7LJAnIEA
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dno0dwbro
  api_key: '117934122311229'
  api_secret: Bt069STFYET5DMuoVbS7LJAnIEA
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dno0dwbro
  api_key: '117934122311229'
  api_secret: Bt069STFYET5DMuoVbS7LJAnIEA
  enhance_image_tag: true
  static_image_support: false